name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  HUSKY: 0
  NODE_VERSION: '22'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Biome (lint/format-check)
        run: pnpm run biome:ci

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test (coverage v8)
        run: pnpm run coverage
