name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  HUSKY: 0
  NODE_VERSION: '22'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (PR head)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          # Ensure we build the PR's head commit (not the merge commit)
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Checkout (push/main)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Biome (lint/format-check)
        run: pnpm run biome:ci:code

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test (coverage v8)
        run: pnpm run coverage
